language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "4"
  - "5"
  - "iojs"
branches:
  only:
    - master
before_install:
  - "npm install -g istanbul"
  - "npm install -g coveralls"
before_script:
  - "npm run lint"
script:
  - "istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec"
after_script:
  - "cat ./coverage/lcov.info | coveralls"
  - "rm -rf ./coverage"
